name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.6'
      - run: ./gradlew clean build
      - uses: actions/upload-artifact@v1
        with:
          name: repo
          path: .
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [build]
    name: Lambda deploy
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: repo
          path: .
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - run: chmod 755 scripts/*
      - run: SKIP_BUILD="TRUE" ./scripts/run.sh deploy-all
